# Give the project a nice name
spring.application.name: person

# Enable all the actuator endpoints for HTTP (keep them under the base path) and JMX
management.endpoints:
  web:
    base-path: /
    exposure.include: "*"
  jmx.exposure.include: "*"

spring.jpa.hibernate.ddl-auto: update

# Do not restart the application when modifying it live
spring.devtools.restart.enabled: false
